add git and snapper setup scripts

diff --git a/scripts/utils b/scripts/utils
--- a/scripts/utils
+++ b/scripts/utils
@@ -1,5 +1,9 @@
 #!/bin/bash
 
+function draw_line() {
+  printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' =
+}
+
 function is_root() {
   if [ "$EUID" -ne 0 ]; then
     echo "Please run as root"
@@ -8,11 +12,15 @@ function is_root() {
 }
 
 function headline() {
-  printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' =
   figlet $1
-  printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' =
 }
 
 function is_service_running() {
-  systemctl is-active --quiet $1 || echo "ERROR: $1 service is not running!" && systemctl status $1 && exit 1
+  if systemctl is-active --quiet $1; then
+    echo "$1 is running :)"
+  else
+    echo "ERROR: $1 is NOT running"
+    systemctl status $1
+    exit 1
+  fi
 }
